Use local GraphQL schema for TS generation
Signed-off-by: David van der Spek <vanderspek.david@gmail.com>

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -82,3 +82,39 @@ jobs:
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
         if: always()
+  updateSchema:
+    name: Check that Schema is up to date
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/checkout@v3
+      - uses: erlef/setup-beam@v1
+        with:
+          version-file: .tool-versions
+          version-type: strict
+      - name: Restore dependencies cache
+        uses: actions/cache@v3
+        with:
+          path: deps
+          key: ${{ runner.os }}-mix-1-${{ hashFiles('**/mix.lock') }}
+          restore-keys: ${{ runner.os }}-mix-1
+      - name: Restore _build
+        uses: actions/cache@v3
+        with:
+          path: _build
+          key: ${{ runner.os }}-mix-1-${{ hashFiles('**/mix.lock') }}
+          restore-keys: ${{ runner.os }}-mix-1
+      - name: get dependencies
+        run: mix deps.get
+      - name: update schema
+        run: MIX_ENV=test mix absinthe.schema.sdl --schema Console.GraphQl  schema/schema.graphql
+      - name: Verify Changed files
+        uses: tj-actions/verify-changed-files@v13
+        id: verify-changed-files
+        with:
+          files: |
+            schema/schema.graphql
+      - name: Schema changed
+        if: steps.verify-changed-files.outputs.files_changed == 'true'
+        run: |
+          echo "::error Schema has changed changed. Please run 'make update-schema' and commit the changes."
+          exit 1
