Begin working on MCP server handling (#2013)

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -127,13 +127,8 @@ jobs:
       - name: update schema
         run: MIX_ENV=test mix absinthe.schema.sdl --schema Console.GraphQl  schema/schema.graphql
       - name: Verify Changed files
-        uses: tj-actions/verify-changed-files@v17
-        id: verify-changed-files
-        with:
-          files: |
-            schema/schema.graphql
-      - name: Schema changed
-        if: steps.verify-changed-files.outputs.files_changed == 'true'
         run: |
-          echo "::error Schema has changed changed. Please run 'make update-schema' and commit the changes."
-          exit 1
+          git diff --exit-code -- schema/schema.graphql || {
+            echo "::error Schema has changed changed. Please run 'make update-schema' and commit the changes."
+            exit 1
+          }
